version: '3'

services:
  mysql:
    container_name: sonamusica_mysql
    image: mysql:8.1.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    env_file:
      - .env
    ports:
      - "3306:3306"
    command: "--log-bin-trust-function-creators=ON"
    volumes:
      - "./scripts/mysql/init_user.sql:/docker-entrypoint-initdb.d/init_user.sql"
      - "./scripts:/scripts"
      - "./data:/data"

  typesense:
    container_name: sonamusica_typesense
    image: typesense/typesense:0.24.1
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: bKf8C5jV6-ctwtEk-HrfPSUqsPwkmmV6BYy9FZZ9GPo
    ports:
      - "8108:8108"
    volumes:
      - ./data/typesense:/data
    command: '--data-dir /data --api-key=bKf8C5jV6-ctwtEk-HrfPSUqsPwkmmV6BYy9FZZ9GPo --enable-cors'
    profiles: ["search"]